const jwt = require("jsonwebtoken");

const auth = (req, res, next) => {
    try {
        const token = req.header("x-auth-token");
        if (!token) {
            return res.status(401).json({ msg: "No authentication token, operation denied.", value: -1 });
        }
        else {
            const verified = jwt.verify(token, process.env.JWT_SECRET); // Was this JWT generated by me ? returns { id: ..., iat: ...} : returns null
            if (!verified) {
                return res.status(401).json({ msg: "Token verification failed, operation denied.", value: 1 });
            }
            else {
                res.user = verified.id;
                res.value = 0;
                next();
            }
        }
    }
    catch (err) {
        res.status(500).json("Error: " + err);
    }
}

module.exports = auth;